// Central list of IPC channel names shared between main and preload/renderer.
export const IPC = {
  roomTypes: {
    list: "roomTypes:list",
    create: "roomTypes:create",
    update: "roomTypes:update",
    delete: "roomTypes:delete",
  },
  rooms: {
    list: "rooms:list",
    create: "rooms:create",
    update: "rooms:update",
    updateStatus: "rooms:updateStatus",
    delete: "rooms:delete",
  },
  guests: {
    list: "guests:list",
    create: "guests:create",
    update: "guests:update",
    delete: "guests:delete",
  },
  bookings: {
    list: "bookings:list",
    create: "bookings:create",
    isRoomAvailable: "bookings:isRoomAvailable",
    cancel: "bookings:cancel",
    checkIn: "bookings:checkIn",
    checkOut: "bookings:checkOut",
    listFolioCharges: "bookings:listFolioCharges",
    addFolioCharge: "bookings:addFolioCharge",
    folioTotal: "bookings:folioTotal",
    listCheckedIn: "bookings:listCheckedIn",
  },
  menuCategories: {
    list: "menuCategories:list",
    create: "menuCategories:create",
    delete: "menuCategories:delete",
  },
  menuItems: {
    list: "menuItems:list",
    create: "menuItems:create",
    update: "menuItems:update",
    delete: "menuItems:delete",
  },
  pos: {
    listOpenOrders: "pos:listOpenOrders",
    createOrder: "pos:createOrder",
    listOrderItems: "pos:listOrderItems",
    addOrderItem: "pos:addOrderItem",
    removeOrderItem: "pos:removeOrderItem",
    orderTotal: "pos:orderTotal",
    voidOrder: "pos:voidOrder",
    checkoutWithPayment: "pos:checkoutWithPayment",
    checkoutToRoom: "pos:checkoutToRoom",
  },
  settings: {
    getGeneral: "settings:getGeneral",
    updateGeneral: "settings:updateGeneral",
    getPaymentMethods: "settings:getPaymentMethods",
    updatePaymentMethods: "settings:updatePaymentMethods",
  },
  currencies: {
    list: "currencies:list",
    create: "currencies:create",
    setBase: "currencies:setBase",
    updateRate: "currencies:updateRate",
    delete: "currencies:delete",
  },
  taxRates: {
    list: "taxRates:list",
    create: "taxRates:create",
    update: "taxRates:update",
    delete: "taxRates:delete",
  },
  numbering: {
    list: "numbering:list",
    update: "numbering:update",
  },
  users: {
    list: "users:list",
    create: "users:create",
    setActive: "users:setActive",
    setRole: "users:setRole",
    login: "users:login",
  },
  backup: {
    getDbPath: "backup:getDbPath",
    backupNow: "backup:backupNow",
    restore: "backup:restore",
    revealDbFolder: "backup:revealDbFolder",
  },
  reports: {
    revenue: "reports:revenue",
    occupancy: "reports:occupancy",
    exportCsv: "reports:exportCsv",
  },
} as const;
